services:
  bot:
    image: ghcr.io/islavok/itmo-schedule:latest
    profiles: [ "prod" ]
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./data:/src/data
      - ./messages.yaml:/src/messages.yaml
      - ./google-credentials.json:/src/google-credentials.json
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - bot_network

  bot-dev:
    build: .
    profiles: [ "dev" ]
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./bot:/src/bot
      - ./app:/src/app
      - ./alembic:/src/alembic
      - ./main.py:/src/main.py
      - ./alembic.ini:/src/alembic.ini
      - ./data:/src/data
      - ./messages.yaml:/src/messages.yaml
      - ./google-credentials.json:/src/google-credentials.json
    networks:
      - bot_network

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    profiles: [ "dev", "prod" ]
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
    networks:
      - bot_network

  postgres:
    image: postgres:17-alpine
    profiles: [ "dev", "prod", "migrate" ]
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - bot_network
    ports:
      - "5434:5432"


  migrate:
    build: .
    profiles: [ "migrate" ]
    env_file:
      - .env
    command: tail -f /dev/null
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./bot:/src/bot
      - ./app:/src/app
      - ./alembic:/src/alembic
      - ./main.py:/src/main.py
      - ./alembic.ini:/src/alembic.ini
      - ./data:/src/data
      - ./messages.yaml:/src/messages.yaml
      - ./google-credentials.json:/src/google-credentials.json
    networks:
      - bot_network

volumes:
  redis_data:
  postgres_data:

networks:
  bot_network:
    driver: bridge