"""add User.rating_notifications

Revision ID: df598b199093
Revises: b9a2138dd8ab
Create Date: 2025-09-29 16:43:25.382015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df598b199093'
down_revision: Union[str, None] = 'b9a2138dd8ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rating_notifications', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.alter_column('users', 'rating_notifications', server_default=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rating_notifications')
    # ### end Alembic commands ###
